import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import mongoose from 'mongoose';

// Load environment variables
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Import the notification service
import notificationService from '../services/notificationService.js';
import User from '../models/User.js';

async function runTest() {
  console.log('🧪 Starting Manual Notification Service Test...\n');

  const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/Hemoconnect';
  
  console.log('🔌 Connecting to MongoDB to fetch a test user...');
  try {
    await mongoose.connect(MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });
    console.log('✅ Connected to MongoDB.');
  } catch (err) {
    console.warn('⚠️  Could not connect to MongoDB. User-specific database lookups will be skipped.');
  }

  // 1. Test Email Configuration
  console.log('\n--- 1. Testing Nodemailer (Gmail SMTP) ---');
  if (process.env.SMTP_USER && process.env.SMTP_PASS) {
    console.log('✅ SMTP_USER and SMTP_PASS env variables are present.');
    const testRecipient = process.env.TEST_EMAIL || process.env.SMTP_USER;
    console.log(`✉️  Attempting to send a test email to: ${testRecipient}...`);
    
    const mockRequest = {
      patientName: 'Test Patient',
      bloodGroup: 'O+',
      unitsRequired: 2,
      hospitalName: 'General Test Hospital',
      requesterName: 'Tester User',
      requesterEmail: testRecipient,
      hospitalRemarks: 'This is a test notification generated by the verification script.'
    };

    const emailHtml = notificationService.buildStatusChangeEmail(mockRequest, 'Approved');
    const emailRes = await notificationService.sendEmail(testRecipient, '🧪 Test Email - HemoConnect', emailHtml);
    
    if (emailRes.success) {
      console.log('✅ Email successfully dispatched via Nodemailer SMTP.');
    } else {
      console.error('❌ Email sending failed. Details:', emailRes);
    }
  } else {
    console.warn('⚠️  SMTP_USER / SMTP_PASS not defined in backend/.env. Skipping email test.');
  }

  // 2. Test Firebase SDK Configuration
  console.log('\n--- 2. Testing Firebase SDK ---');
  const serviceAccountPath = process.env.FIREBASE_SERVICE_ACCOUNT_PATH 
    || path.resolve(__dirname, '..', 'firebase-service-account.json');

  console.log(`Checking for Firebase credentials at: ${serviceAccountPath}`);
  
  // Try to find a user in the database with FCM tokens to test push sending
  if (mongoose.connection.readyState === 1) {
    try {
      const userWithTokens = await User.findOne({ 'fcmTokens.0': { $exists: true } });
      if (userWithTokens) {
        console.log(`📱 Found user in database with active FCM tokens: ${userWithTokens.email}`);
        console.log('Sending test push notification...');
        const pushRes = await notificationService.sendPushNotification(
          userWithTokens._id,
          '🧪 Test Push Notification',
          'This is a manual test notification from the verification script.',
          { test: 'true' }
        );
        console.log('Push Result:', pushRes);
      } else {
        console.log('ℹ️  No users found in MongoDB database with registered FCM tokens. Build/run the app and login to register a device token first.');
      }
    } catch (err) {
      console.error('❌ Error testing database push token lookup:', err.message);
    }
  } else {
    console.log('ℹ️  MongoDB connection offline. Skipping live database token push test.');
  }

  if (mongoose.connection.readyState === 1) {
    await mongoose.disconnect();
    console.log('\n🔌 Disconnected from MongoDB.');
  }

  console.log('\n🏁 Verification complete.');
}

runTest().catch(console.error);
